export type DslCategory = 'Project' | 'Model' | 'Signals' | 'Topology' | 'Control' | 'PLC' | 'Presentation' | 'Reports';

export type DslEntity = {
  name: string;
  signature: string;
  category: DslCategory;
  textKey: string;
  relations: string[];
  example: string;
  featured?: boolean;
};

export const entities: DslEntity[] = [
  {
    name: 'project',
    textKey: 'project',
    signature: 'project(name, options) → Project',
    category: 'Project',
    relations: ['system', 'simulation', 'control', 'plc', 'pipe', 'alarm', 'report'],
    example: `export default project('water-station', {
  title: 'Насосная станция',
  description: 'Основной контур',
  systems: [water],
  simulations: [pump],
  controls: [speed],
  connections: [suction],
  signals: [],
  alarms: [],
  reports: [],
})`,
  },
  {
    name: 'system',
    textKey: 'system',
    signature: 'system(name, title, parent?) → System',
    category: 'Project',
    relations: ['project', 'simulation', 'equipment', 'control', 'plc'],
    example: `const water = system('water', 'Водоснабжение')
const pumps = system('pumps', 'Насосная группа', 'water')`,
  },
  {
    name: 'simulation',
    textKey: 'simulation',
    signature: 'simulation(name, model, options) → SimRef',
    category: 'Model',
    relations: ['system', 'signal', 'derived', 'equipment', 'port', 'pipe'],
    example: `const pump = simulation('P-101', 'pump', {
  system: 'water',
  at: { x: 320, y: 180 },
  inputs: { voltage: drive.value },
  parameters: { inertia: 1.6 },
})

// pump.rpm  → SignalRef<..., number, 'об/мин', 'rotational-speed'>
// pump.flow → SignalRef<..., number, 'отн.', 'flow'>`,
  },
  {
    name: 'equipment',
    textKey: 'equipment',
    signature: 'equipment(name, type, { system, at, signals }) → Device',
    category: 'Model',
    relations: ['simulation', 'signal', 'system', 'port'],
    example: `const gauge = equipment('FI-101', 'sensor', {
  system: 'water',
  at: { x: 620, y: 150 },
  signals: { value: pump.flow },
})`,
  },
  {
    name: 'signal',
    textKey: 'signal',
    signature: 'signal(path) → SignalRef',
    category: 'Signals',
    relations: ['simulation', 'derived', 'alarm', 'control', 'view'],
    example: `const pressure = signal('PT-101.value')`,
  },
  {
    name: 'derived',
    textKey: 'derived',
    signature: 'derived(name, expression, unit?, history?) → Derived',
    category: 'Signals',
    relations: ['signal', 'aggregate', 'alarm', 'report'],
    example: `const power = derived(
  'P-101.power',
  mul(signal('P-101.voltage'), signal('P-101.current')),
  'kW',
)`,
  },
  {
    name: 'bank',
    textKey: 'bank',
    signature: 'bank(prefix, model, options) → SimRef[]',
    category: 'Model',
    relations: ['simulation', 'aggregate', 'system'],
    example: `const pumps = bank('P-', 'pump', {
  count: 4,
  columns: 2,
  pitch: { x: 260, y: 180 },
  system: 'water',
  at: { x: 200, y: 120 },
})`,
  },
  {
    name: 'aggregate',
    textKey: 'aggregate',
    signature: "aggregate(items, output, operation = 'mean') → Expr<number, DimensionOf<output>>",
    category: 'Signals',
    relations: ['bank', 'derived', 'signal'],
    example: `const totalFlow = derived(
  'water.totalFlow',
  aggregate(pumps, 'flow', 'sum'),
  'm³/h',
)`,
  },
  {
    name: 'control',
    textKey: 'control',
    signature: 'control(name, options) → ControlRef',
    category: 'Control',
    relations: ['project', 'signal', 'view', 'plc'],
    example: `const drive = control('P-101.speed', {
  title: 'Скорость насоса',
  system: 'water',
  min: 0,
  max: 1,
  initial: 0.6,
  rate: 0.25,
})`,
  },
  {
    name: 'port',
    textKey: 'port',
    signature: 'port(device, name) → Endpoint',
    category: 'Topology',
    relations: ['simulation', 'equipment', 'plc', 'pipe', 'cable'],
    example: `const inlet = port(pump, 'inlet')
const outlet = port(pump, 'outlet')`,
  },
  {
    name: 'pipe',
    textKey: 'pipe',
    signature: 'pipe(name, from, to, { via? }) → Connection',
    category: 'Topology',
    relations: ['port', 'simulation', 'equipment', 'project'],
    example: `const suction = pipe(
  'suction',
  port(tank, 'outlet'),
  port(pump, 'inlet'),
)`,
    featured: true,
  },
  {
    name: 'cable',
    textKey: 'cable',
    signature: 'cable(name, from, to, options) → Connection',
    category: 'Topology',
    relations: ['port', 'plc', 'equipment', 'project'],
    example: `const power = cable(
  'pump-power',
  port(feeder, 'out'),
  port(pumpDrive, 'power'),
  { medium: 'power' },
)`,
  },
  {
    name: 'expansion',
    textKey: 'expansion',
    signature: 'expansion(device, controller, slot) → Attachment',
    category: 'Topology',
    relations: ['plc', 'simulation', 'project'],
    example: `const ai4 = expansion(module, controller, 1)`,
  },
  {
    name: 'plc',
    textKey: 'plc',
    signature: 'plc(name, { system, at, outputs, blocks, hmi? }) → ControllerRef',
    category: 'PLC',
    relations: ['pin', 'block', 'functionBlock', 'port', 'cable', 'expansion'],
    example: `const controller = plc('SATURN-1', {
  system: 'control',
  at: { x: 800, y: 280 },
  blocks: {},
  outputs: {
    DO1: gt(pin('AI1'), 500),
  },
})`,
  },
  {
    name: 'pin',
    textKey: 'pin',
    signature: 'pin(name) → Expr',
    category: 'PLC',
    relations: ['plc', 'functionBlock', 'block'],
    example: `const high = gt(pin('AI1'), 500)`,
  },
  {
    name: 'block',
    textKey: 'block',
    signature: 'block(name) → Expr',
    category: 'PLC',
    relations: ['plc', 'functionBlock', 'pin'],
    example: `const delayed = block('START_DELAY')`,
  },
  {
    name: 'functionBlock',
    textKey: 'functionBlock',
    signature: 'functionBlock(type, inputs, params?) → PlcBlock',
    category: 'PLC',
    relations: ['plc', 'pin', 'block'],
    example: `const delay = functionBlock('TON', [pin('DI1')], [500])`,
  },
  {
    name: 'alarm',
    textKey: 'alarm',
    signature: 'alarm(name, options) → AlarmRule',
    category: 'Control',
    relations: ['signal', 'derived', 'project'],
    example: `const hot = alarm('P-101-hot', {
  title: 'Перегрев P-101',
  signal: pump.temperature,
  above: 80,
  clearBelow: 75,
  priority: 'critical',
})`,
  },
  {
    name: 'reportField',
    textKey: 'reportField',
    signature: 'reportField(signalRef) → ReportFieldRef',
    category: 'Reports',
    relations: ['reportSchema', 'report', 'excelColumn'],
    example: `const flow = reportField(pump.flow)`,
  },
  {
    name: 'numberField',
    textKey: 'numberField',
    signature: 'numberField(unit?) → ReportFieldRef<number>',
    category: 'Reports',
    relations: ['reportSchema', 'reportColumn'],
    example: `const time = numberField('ms')`,
  },
  {
    name: 'booleanField',
    textKey: 'booleanField',
    signature: 'booleanField() → ReportFieldRef<boolean>',
    category: 'Reports',
    relations: ['reportSchema', 'excelColumn'],
    example: `const active = booleanField()`,
  },
  {
    name: 'textField',
    textKey: 'textField',
    signature: 'textField() → ReportFieldRef<string>',
    category: 'Reports',
    relations: ['reportSchema', 'excelColumn'],
    example: `const name = textField()`,
  },
  {
    name: 'dateTimeField',
    textKey: 'dateTimeField',
    signature: 'dateTimeField() → ReportFieldRef<Date>',
    category: 'Reports',
    relations: ['reportSchema', 'excelColumn'],
    example: `const timestamp = dateTimeField()`,
  },
  {
    name: 'reportSchema',
    textKey: 'reportSchema',
    signature: 'reportSchema(fields) → ReportSchema',
    category: 'Reports',
    relations: ['reportField', 'reportColumn', 'excelSheet'],
    example: `const rows = reportSchema({ flow: reportField(pump.flow), time: numberField('ms') })`,
  },
  {
    name: 'reportColumn',
    textKey: 'reportColumn',
    signature: 'reportColumn(title, field) → ReportColumn',
    category: 'Reports',
    relations: ['reportSchema', 'report'],
    example: `reportColumn('Расход', rows.flow)`,
  },
  {
    name: 'excelColumn',
    textKey: 'excelColumn',
    signature: 'excelColumn(title, field, options?) → ExcelColumn',
    category: 'Reports',
    relations: ['excelSheet', 'reportField'],
    example: `excelColumn('Расход', rows.flow, { format: '0.00' })`,
  },
  {
    name: 'asc',
    textKey: 'asc',
    signature: 'asc(field) → ExcelSort',
    category: 'Reports',
    relations: ['excelSheet', 'desc'],
    example: `asc(rows.time)`,
  },
  {
    name: 'desc',
    textKey: 'desc',
    signature: 'desc(field) → ExcelSort',
    category: 'Reports',
    relations: ['excelSheet', 'asc'],
    example: `desc(rows.flow)`,
  },
  {
    name: 'excelSheet',
    textKey: 'excelSheet',
    signature: 'excelSheet(name, schema, options) → ExcelSheet',
    category: 'Reports',
    relations: ['workbook', 'excelColumn', 'asc', 'desc'],
    example: `excelSheet('Расход', rows, { columns: [excelColumn('Расход', rows.flow)], sort: [desc(rows.flow)] })`,
  },
  {
    name: 'workbook',
    textKey: 'workbook',
    signature: 'workbook(sheets) → ExcelWorkbook',
    category: 'Reports',
    relations: ['excelSheet', 'report'],
    example: `workbook([excelSheet('Расход', rows, { columns: [excelColumn('Расход', rows.flow)] })])`,
  },
  {
    name: 'report',
    textKey: 'report',
    signature: 'report(name, options) → Report',
    category: 'Reports',
    relations: ['signal', 'derived', 'view', 'project'],
    example: `const hourly = report('flow-hour', {
  title: 'Расход за час',
  on: { schedule: [{ cron: '0 * * * *' }] },
  signals: [pump.flow],
  window: 3_600_000,
  sql: 'SELECT signal, AVG(value) AS average FROM samples GROUP BY signal',
  columns: [
    { key: 'signal', title: 'Сигнал' },
    { key: 'average', title: 'Среднее' },
  ],
})`,
  },
  {
    name: 'view',
    textKey: 'view',
    signature: 'view(name, options) → Presentation',
    category: 'Presentation',
    relations: ['panel', 'readout', 'commandButton', 'signal', 'control', 'report'],
    example: `const operator = view('operator', {
  title: 'Насосная',
  bindings: { rpm: pump.rpm, flow: pump.flow },
  body: panel([
    readout('Обороты', 'rpm', 'об/мин', 0),
    readout('Расход', 'flow', 'м³/ч', 1),
  ]),
})`,
  },
  {
    name: 'panel',
    textKey: 'panel',
    signature: "panel(children, direction = 'column', title?) → ViewNode",
    category: 'Presentation',
    relations: ['view', 'readout', 'commandButton'],
    example: `panel([
  readout('Расход', 'flow', 'м³/ч'),
  commandButton('Стоп', 'P-101.speed', 0),
], 'column', 'P-101')`,
  },
  {
    name: 'readout',
    textKey: 'readout',
    signature: "readout(label, binding, unit = '', digits = 2) → ViewNode",
    category: 'Presentation',
    relations: ['view', 'signal', 'panel'],
    example: `readout('Обороты', 'rpm', 'об/мин', 0)`,
  },
  {
    name: 'label',
    textKey: 'label',
    signature: 'label(text) → ViewNode',
    category: 'Presentation',
    relations: ['view', 'panel', 'readout'],
    example: `label('Насосная станция')`,
  },
  {
    name: 'dataTable',
    textKey: 'dataTable',
    signature: 'dataTable(columns) → ViewNode',
    category: 'Presentation',
    relations: ['view', 'report', 'panel'],
    example: `dataTable([
  { key: 'signal', title: 'Сигнал' },
  { key: 'average', title: 'Среднее', unit: 'м³/ч' },
])`,
  },
  {
    name: 'trend',
    textKey: 'trend',
    signature: 'trend(title, x, y) → ViewNode',
    category: 'Presentation',
    relations: ['view', 'report', 'dataTable'],
    example: `trend('Расход', 'time', 'flow')`,
  },
  {
    name: 'commandButton',
    textKey: 'commandButton',
    signature: 'commandButton(label, target, value) → ViewNode',
    category: 'Presentation',
    relations: ['view', 'control', 'panel'],
    example: `commandButton('Пуск', 'P-101.speed', 0.64)`,
  },
];

export const operators = [
  ['add', 'add(...expr)'],
  ['sub', 'sub(a, b)'],
  ['mul', 'mul(...expr)'],
  ['div', 'div(a, b)'],
  ['min', 'min(...expr)'],
  ['max', 'max(...expr)'],
  ['gt', 'gt(a, b)'],
  ['lt', 'lt(a, b)'],
  ['and', 'and(...expr)'],
] as const;

